# Generated by Django 2.0.7 on 2018-08-01 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_num', models.CharField(max_length=20, verbose_name='用例编号')),
                ('name', models.CharField(max_length=18, verbose_name='用例标题')),
                ('type', models.CharField(choices=[('web', 'Web自动化'), ('app', 'App自动化'), ('inface', '接口自动化')], max_length=20, verbose_name='用例类型')),
                ('expect', models.CharField(max_length=50, verbose_name='期望结果')),
                ('status', models.CharField(choices=[('idle', '未执行'), ('success', '通过'), ('fail', '失败')], max_length=20, verbose_name='结果')),
                ('level', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高')], max_length=20, verbose_name='用例级别')),
                ('detail', models.CharField(max_length=50, verbose_name='模块描述')),
                ('remark', models.TextField(blank=True, max_length=200, verbose_name='备注')),
                ('add_time', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('edit_time', models.DateField(auto_now=True, verbose_name='修改时间')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '用例库',
                'verbose_name_plural': '用例库',
            },
        ),
        migrations.CreateModel(
            name='CasesStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_seqnum', models.IntegerField(default=1, verbose_name='操作步骤顺序号')),
                ('add_time', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('edit_time', models.DateField(auto_now=True, verbose_name='修改时间')),
                ('case_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='RobotManager.Cases', verbose_name='测试用例')),
            ],
            options={
                'verbose_name': '用例操作步骤',
                'verbose_name_plural': '用例操作步骤',
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='关键字名称')),
                ('doc', models.CharField(max_length=50, verbose_name='关键字描述')),
                ('add_time', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('edit_time', models.DateField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '关键字库',
                'verbose_name_plural': '关键字库',
            },
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Library名称')),
                ('doc', models.CharField(max_length=50, verbose_name='Library名描述')),
                ('add_time', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('edit_time', models.DateField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '公用测试库',
                'verbose_name_plural': '公用测试库',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=18, verbose_name='模块名称')),
                ('detail', models.CharField(max_length=50, verbose_name='模块描述')),
                ('remark', models.TextField(blank=True, max_length=200, null=True, verbose_name='备注')),
                ('add_time', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('edit_time', models.DateField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '测试模块',
                'verbose_name_plural': '测试模块',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=18, verbose_name='项目名称')),
                ('type', models.CharField(choices=[('web', 'Web自动化'), ('app', 'App自动化'), ('inface', '接口自动化')], max_length=20, verbose_name='项目类型')),
                ('detail', models.CharField(max_length=50, verbose_name='项目描述')),
                ('remark', models.TextField(max_length=200, verbose_name='备注')),
                ('addtime', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('edittime', models.DateField(auto_now=True, verbose_name='修改时间')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '测试项目',
                'verbose_name_plural': '测试项目',
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Resource名称')),
                ('doc', models.CharField(max_length=100, verbose_name='Resource描述')),
                ('add_time', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('edit_time', models.DateField(auto_now=True, verbose_name='修改时间')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='RobotManager.Module', verbose_name='所属模块')),
            ],
            options={
                'verbose_name': 'Resource库',
                'verbose_name_plural': 'Resource库',
            },
        ),
        migrations.CreateModel(
            name='Steps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_num', models.IntegerField(verbose_name='步骤顺序号')),
                ('name', models.CharField(max_length=18, verbose_name='操作步骤名称')),
                ('doc', models.CharField(blank=True, max_length=50, null=True, verbose_name='操作步骤描述')),
                ('remark', models.TextField(blank=True, max_length=200, verbose_name='备注')),
                ('add_time', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('edit_time', models.DateField(auto_now=True, verbose_name='修改时间')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '操作步骤库',
                'verbose_name_plural': '操作步骤库',
            },
        ),
        migrations.CreateModel(
            name='Suites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suite_num', models.CharField(max_length=20, verbose_name='测试集编号')),
                ('name', models.CharField(max_length=18, verbose_name='测试集名称')),
                ('detail', models.CharField(max_length=50, verbose_name='测试集描述')),
                ('remark', models.TextField(blank=True, max_length=200, verbose_name='备注')),
                ('add_time', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('edit_time', models.DateField(auto_now=True, verbose_name='修改时间')),
                ('belong_module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='RobotManager.Module', verbose_name='所属模块')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '测试集',
                'verbose_name_plural': '测试集',
            },
        ),
        migrations.CreateModel(
            name='UserKeywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='用户关键字名称')),
                ('doc', models.CharField(max_length=100, verbose_name='用户关键字描述')),
                ('add_time', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('edit_time', models.DateField(auto_now=True, verbose_name='修改时间')),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='RobotManager.Resource', verbose_name='所属Resource')),
            ],
            options={
                'verbose_name': '用户关键字库',
                'verbose_name_plural': '用户关键字库',
            },
        ),
        migrations.AddField(
            model_name='steps',
            name='keyword',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='RobotManager.UserKeywords'),
        ),
        migrations.AddField(
            model_name='module',
            name='belong_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='RobotManager.Project', verbose_name='所属项目'),
        ),
        migrations.AddField(
            model_name='module',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='keyword',
            name='library',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='RobotManager.Library', verbose_name='所属Library'),
        ),
        migrations.AddField(
            model_name='casesstep',
            name='step_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='RobotManager.Steps', verbose_name='操作步骤'),
        ),
        migrations.AddField(
            model_name='cases',
            name='suite',
            field=models.ManyToManyField(to='RobotManager.Suites', verbose_name='测试集'),
        ),
    ]
