# Generated by Django 2.0.7 on 2018-08-01 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RobotManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userkeywords',
            name='keyword',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='RobotManager.Keyword'),
        ),
        migrations.AddField(
            model_name='userkeywords',
            name='relate_user_keyword',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='RobotManager.UserKeywords', verbose_name='关联用户关键字'),
        ),
        migrations.AlterField(
            model_name='cases',
            name='detail',
            field=models.CharField(max_length=50, verbose_name='用例描述'),
        ),
    ]
