# Generated by Django 2.0.7 on 2018-08-05 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RobotManager', '0002_auto_20180802_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Library名称'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=18, unique=True, verbose_name='项目名称'),
        ),
    ]
