# Generated by Django 2.0.7 on 2018-10-17 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RobotManager', '0003_auto_20180805_1804'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='addtime',
            new_name='add_time',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='edittime',
            new_name='edit_time',
        ),
    ]
